export type Question = {
  prompt: string;
  options: [string, string, string, string];
  correctIndex: 0 | 1 | 2 | 3;
};

/** ~100 domande di cultura generale, senza contenuto legato alla coppia (quello è dominio di F5). */
export const QUESTIONS: Question[] = [
  { prompt: 'What is the capital of Japan?', options: ['Tokyo', 'Osaka', 'Kyoto', 'Nagoya'], correctIndex: 0 },
  { prompt: 'What is the capital of France?', options: ['Paris', 'Lyon', 'Marseille', 'Nice'], correctIndex: 0 },
  { prompt: 'What is the capital of Italy?', options: ['Rome', 'Milan', 'Naples', 'Venice'], correctIndex: 0 },
  { prompt: 'What is the capital of Australia?', options: ['Sydney', 'Canberra', 'Melbourne', 'Perth'], correctIndex: 1 },
  { prompt: 'What is the capital of Canada?', options: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'], correctIndex: 1 },
  { prompt: 'What is the capital of Brazil?', options: ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador'], correctIndex: 2 },
  { prompt: 'Which is the largest ocean on Earth?', options: ['Atlantic', 'Pacific', 'Indian', 'Arctic'], correctIndex: 1 },
  { prompt: 'Which is the largest continent by area?', options: ['Africa', 'Asia', 'North America', 'Europe'], correctIndex: 1 },
  { prompt: 'Which is the smallest continent?', options: ['Europe', 'Antarctica', 'Australia', 'South America'], correctIndex: 2 },
  { prompt: 'What is traditionally considered the longest river in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], correctIndex: 1 },
  { prompt: 'What is the tallest mountain in the world?', options: ['K2', 'Kilimanjaro', 'Everest', 'Denali'], correctIndex: 2 },
  { prompt: 'What is the largest hot desert in the world?', options: ['Gobi', 'Kalahari', 'Sahara', 'Mojave'], correctIndex: 2 },
  { prompt: 'How many continents are there?', options: ['5', '6', '7', '8'], correctIndex: 2 },
  { prompt: 'Which country is known as the "Land of the Rising Sun"?', options: ['China', 'Japan', 'South Korea', 'Thailand'], correctIndex: 1 },
  { prompt: 'The Great Barrier Reef is located near which country?', options: ['New Zealand', 'Australia', 'Indonesia', 'Fiji'], correctIndex: 1 },
  { prompt: 'What is the chemical symbol for gold?', options: ['Ag', 'Au', 'Gd', 'Go'], correctIndex: 1 },
  { prompt: 'What is the chemical formula for water?', options: ['CO2', 'H2O', 'O2', 'NaCl'], correctIndex: 1 },
  { prompt: 'Which planet is closest to the sun?', options: ['Venus', 'Earth', 'Mercury', 'Mars'], correctIndex: 2 },
  { prompt: 'How many planets are in our solar system?', options: ['7', '8', '9', '10'], correctIndex: 1 },
  { prompt: 'Approximately how fast does light travel?', options: ['150,000 km/s', '300,000 km/s', '450,000 km/s', '600,000 km/s'], correctIndex: 1 },
  { prompt: 'What gas do plants absorb for photosynthesis?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], correctIndex: 2 },
  { prompt: "What is the largest organ of the human body?", options: ['Liver', 'Heart', 'Skin', 'Lungs'], correctIndex: 2 },
  { prompt: 'How many bones are in the adult human body?', options: ['186', '196', '206', '216'], correctIndex: 2 },
  { prompt: 'What force pulls objects toward the Earth?', options: ['Magnetism', 'Gravity', 'Friction', 'Inertia'], correctIndex: 1 },
  { prompt: 'What is the chemical symbol for oxygen?', options: ['O', 'Ox', 'O2', 'Og'], correctIndex: 0 },
  { prompt: 'What is the freezing point of water in Celsius?', options: ['-10', '0', '10', '32'], correctIndex: 1 },
  { prompt: 'What is the boiling point of water in Celsius at sea level?', options: ['90', '100', '110', '120'], correctIndex: 1 },
  { prompt: 'What is often called the "powerhouse of the cell"?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi apparatus'], correctIndex: 2 },
  { prompt: 'What do bees primarily produce?', options: ['Silk', 'Honey', 'Wax only', 'Pollen only'], correctIndex: 1 },
  { prompt: 'What is the scientific study of living organisms called?', options: ['Geology', 'Biology', 'Astronomy', 'Chemistry'], correctIndex: 1 },
  { prompt: 'Who painted the Mona Lisa?', options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'], correctIndex: 1 },
  { prompt: 'In which year did World War II end?', options: ['1943', '1944', '1945', '1946'], correctIndex: 2 },
  { prompt: 'Who was the first President of the United States?', options: ['Thomas Jefferson', 'John Adams', 'Benjamin Franklin', 'George Washington'], correctIndex: 3 },
  { prompt: 'The Great Wall is located in which country?', options: ['India', 'China', 'Mongolia', 'Japan'], correctIndex: 1 },
  { prompt: 'Which ancient civilization built the pyramids of Giza?', options: ['Romans', 'Greeks', 'Egyptians', 'Persians'], correctIndex: 2 },
  { prompt: 'In which year did the Titanic sink?', options: ['1910', '1912', '1914', '1916'], correctIndex: 1 },
  { prompt: 'Who developed the theory of relativity?', options: ['Isaac Newton', 'Albert Einstein', 'Nikola Tesla', 'Galileo Galilei'], correctIndex: 1 },
  { prompt: "The Roman Empire's capital was which city?", options: ['Athens', 'Rome', 'Constantinople', 'Carthage'], correctIndex: 1 },
  { prompt: 'Which war was fought between the North and South United States?', options: ['Revolutionary War', 'Civil War', 'War of 1812', 'Cold War'], correctIndex: 1 },
  { prompt: 'Who was known as the "Maid of Orléans"?', options: ['Marie Antoinette', 'Joan of Arc', 'Catherine the Great', 'Cleopatra'], correctIndex: 1 },
  { prompt: 'Who wrote "Romeo and Juliet"?', options: ['Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Jane Austen'], correctIndex: 1 },
  { prompt: 'In Harry Potter, which house is Harry sorted into?', options: ['Slytherin', 'Hufflepuff', 'Ravenclaw', 'Gryffindor'], correctIndex: 3 },
  { prompt: 'Who wrote "Pride and Prejudice"?', options: ['Jane Austen', 'Emily Brontë', 'Virginia Woolf', 'Mary Shelley'], correctIndex: 0 },
  { prompt: 'What is the wizard school in Harry Potter called?', options: ['Hogwarts', 'Durmstrang', 'Beauxbatons', 'Ilvermorny'], correctIndex: 0 },
  { prompt: 'Who directed the movie "Jaws"?', options: ['George Lucas', 'Steven Spielberg', 'James Cameron', 'Martin Scorsese'], correctIndex: 1 },
  { prompt: "What is Batman's secret identity?", options: ['Clark Kent', 'Tony Stark', 'Bruce Wayne', 'Peter Parker'], correctIndex: 2 },
  { prompt: "In The Lion King, who is Simba's father?", options: ['Scar', 'Mufasa', 'Zazu', 'Rafiki'], correctIndex: 1 },
  { prompt: 'Which fruit poisons Snow White?', options: ['Pear', 'Apple', 'Peach', 'Cherry'], correctIndex: 1 },
  { prompt: 'Who wrote the novel "1984"?', options: ['Aldous Huxley', 'Ray Bradbury', 'George Orwell', 'H.G. Wells'], correctIndex: 2 },
  { prompt: "What are the primary colors of Spider-Man's suit?", options: ['Blue and black', 'Red and blue', 'Green and black', 'Red and gold'], correctIndex: 1 },
  { prompt: 'How many players are on a soccer team on the field?', options: ['9', '10', '11', '12'], correctIndex: 2 },
  { prompt: 'In tennis, what is a score of zero called?', options: ['Nil', 'Love', 'Zero', 'Duck'], correctIndex: 1 },
  { prompt: 'How many rings are on the Olympic flag?', options: ['4', '5', '6', '7'], correctIndex: 1 },
  { prompt: 'In which sport would you perform a "slam dunk"?', options: ['Volleyball', 'Basketball', 'Tennis', 'Baseball'], correctIndex: 1 },
  { prompt: 'How many players are on a basketball team on the court?', options: ['4', '5', '6', '7'], correctIndex: 1 },
  { prompt: 'What sport is played at Wimbledon?', options: ['Golf', 'Cricket', 'Tennis', 'Rugby'], correctIndex: 2 },
  { prompt: 'How many holes are played in a standard round of golf?', options: ['9', '16', '18', '20'], correctIndex: 2 },
  { prompt: 'What is the national sport of Japan?', options: ['Judo', 'Karate', 'Sumo wrestling', 'Baseball'], correctIndex: 2 },
  { prompt: 'How many minutes is a standard boxing round?', options: ['2', '3', '4', '5'], correctIndex: 1 },
  { prompt: 'Which country is credited with inventing table tennis?', options: ['China', 'Japan', 'England', 'USA'], correctIndex: 2 },
  { prompt: 'What is the main ingredient in guacamole?', options: ['Tomato', 'Avocado', 'Lime', 'Onion'], correctIndex: 1 },
  { prompt: 'Which spice is derived from the Crocus flower?', options: ['Cinnamon', 'Paprika', 'Saffron', 'Turmeric'], correctIndex: 2 },
  { prompt: 'Sushi originated in which country?', options: ['China', 'Japan', 'Korea', 'Thailand'], correctIndex: 1 },
  { prompt: 'Which country is credited as the origin of pizza?', options: ['Greece', 'Spain', 'Italy', 'France'], correctIndex: 2 },
  { prompt: 'What is the main ingredient in hummus?', options: ['Lentils', 'Chickpeas', 'Black beans', 'Peas'], correctIndex: 1 },
  { prompt: 'Which fruit is known as the "king of fruits"?', options: ['Mango', 'Pineapple', 'Durian', 'Jackfruit'], correctIndex: 2 },
  { prompt: 'Champagne is a type of what?', options: ['Beer', 'Sparkling wine', 'Whisky', 'Cider'], correctIndex: 1 },
  { prompt: 'Which country produces the most coffee?', options: ['Colombia', 'Vietnam', 'Brazil', 'Ethiopia'], correctIndex: 2 },
  { prompt: 'Tofu is made from which ingredient?', options: ['Rice', 'Soybeans', 'Chickpeas', 'Wheat'], correctIndex: 1 },
  { prompt: 'What is the primary ingredient in traditional bread?', options: ['Sugar', 'Flour', 'Butter', 'Yeast'], correctIndex: 1 },
  { prompt: 'What is the fastest land animal?', options: ['Lion', 'Cheetah', 'Horse', 'Antelope'], correctIndex: 1 },
  { prompt: 'What is the largest mammal in the world?', options: ['Elephant', 'Blue whale', 'Giraffe', 'Hippopotamus'], correctIndex: 1 },
  { prompt: 'How many legs does a spider have?', options: ['6', '8', '10', '12'], correctIndex: 1 },
  { prompt: 'What is a group of lions called?', options: ['Pack', 'Herd', 'Pride', 'Flock'], correctIndex: 2 },
  { prompt: 'Which flightless bird is the fastest runner among birds?', options: ['Penguin', 'Emu', 'Ostrich', 'Kiwi'], correctIndex: 2 },
  { prompt: 'What is the tallest animal in the world?', options: ['Elephant', 'Giraffe', 'Camel', 'Moose'], correctIndex: 1 },
  { prompt: 'How many hearts does an octopus have?', options: ['1', '2', '3', '4'], correctIndex: 2 },
  { prompt: 'What is a baby kangaroo called?', options: ['Cub', 'Joey', 'Kid', 'Pup'], correctIndex: 1 },
  { prompt: 'Which animal is known as "man\'s best friend"?', options: ['Cat', 'Horse', 'Dog', 'Parrot'], correctIndex: 2 },
  { prompt: 'What is the only mammal capable of true flight?', options: ['Flying squirrel', 'Bat', 'Sugar glider', 'Colugo'], correctIndex: 1 },
  { prompt: 'How many days are in a leap year?', options: ['364', '365', '366', '367'], correctIndex: 2 },
  { prompt: 'How many colors are traditionally listed in a rainbow?', options: ['5', '6', '7', '8'], correctIndex: 2 },
  { prompt: 'What is the currency of Japan?', options: ['Won', 'Yuan', 'Yen', 'Ringgit'], correctIndex: 2 },
  { prompt: 'What is the currency of the United Kingdom?', options: ['Euro', 'Pound', 'Franc', 'Krona'], correctIndex: 1 },
  { prompt: 'How many strings does a standard guitar have?', options: ['4', '5', '6', '7'], correctIndex: 2 },
  { prompt: 'Which is the tallest building in the world?', options: ['Shanghai Tower', 'Burj Khalifa', 'One World Trade Center', 'Taipei 101'], correctIndex: 1 },
  { prompt: 'Which language has the most native speakers worldwide?', options: ['English', 'Spanish', 'Mandarin Chinese', 'Hindi'], correctIndex: 2 },
  { prompt: 'How many minutes are in a full day?', options: ['1200', '1440', '1600', '1800'], correctIndex: 1 },
  { prompt: 'What is the largest planet in the solar system?', options: ['Saturn', 'Jupiter', 'Neptune', 'Uranus'], correctIndex: 1 },
  { prompt: 'What shape has exactly 3 sides?', options: ['Square', 'Pentagon', 'Triangle', 'Hexagon'], correctIndex: 2 },
  { prompt: 'How many sides does a hexagon have?', options: ['5', '6', '7', '8'], correctIndex: 1 },
  { prompt: 'What is the chemical symbol for table salt?', options: ['NaCl', 'KCl', 'CaCl', 'NaOH'], correctIndex: 0 },
  { prompt: 'Who is credited as the inventor of the telephone?', options: ['Thomas Edison', 'Alexander Graham Bell', 'Nikola Tesla', 'Guglielmo Marconi'], correctIndex: 1 },
  { prompt: 'What does "www" stand for?', options: ['World Web Wide', 'World Wide Web', 'Wide World Web', 'Web World Wide'], correctIndex: 1 },
  { prompt: 'Which planet is known as the "Red Planet"?', options: ['Venus', 'Jupiter', 'Mars', 'Mercury'], correctIndex: 2 },
  { prompt: 'What is the largest island in the world?', options: ['Madagascar', 'Greenland', 'Borneo', 'New Guinea'], correctIndex: 1 },
  { prompt: 'How many letters are in the English alphabet?', options: ['24', '25', '26', '27'], correctIndex: 2 },
  { prompt: 'What is the hardest natural substance on Earth?', options: ['Gold', 'Quartz', 'Diamond', 'Titanium'], correctIndex: 2 },
  { prompt: 'Which instrument typically has 88 keys?', options: ['Organ', 'Piano', 'Harpsichord', 'Accordion'], correctIndex: 1 },
  { prompt: 'What is the national language of Brazil?', options: ['Spanish', 'Portuguese', 'French', 'Italian'], correctIndex: 1 },
];
