-- Costi per categoria (spec F4.1, sezione 6): domestico/fattoria 35,
-- esotico 70, fantastico 140, piante 25. Le chiavi sono definitive: sono
-- anche i nomi dei file immagine attesi in public/pets/<key>.png.
insert into item_prices (key, cost, label) values
  ('pet_dog', 35, 'Dog'),
  ('pet_cat', 35, 'Cat'),
  ('pet_rabbit', 35, 'Rabbit'),
  ('pet_hamster', 35, 'Hamster'),
  ('pet_guinea_pig', 35, 'Guinea pig'),
  ('pet_parrot', 35, 'Parrot'),
  ('pet_goldfish', 35, 'Goldfish'),
  ('pet_turtle', 35, 'Turtle'),
  ('pet_pony', 35, 'Pony'),
  ('pet_goat', 35, 'Goat'),
  ('pet_sheep', 35, 'Sheep'),
  ('pet_cow', 35, 'Cow'),
  ('pet_pig', 35, 'Pig'),
  ('pet_capybara', 35, 'Capybara'),
  ('pet_koala', 70, 'Koala'),
  ('pet_panda', 70, 'Panda'),
  ('pet_penguin', 70, 'Penguin'),
  ('pet_fox', 70, 'Fox'),
  ('pet_owl', 70, 'Owl'),
  ('pet_sloth', 70, 'Sloth'),
  ('pet_otter', 70, 'Otter'),
  ('pet_hedgehog', 70, 'Hedgehog'),
  ('pet_chameleon', 70, 'Chameleon'),
  ('pet_flamingo', 70, 'Flamingo'),
  ('pet_unicorn', 140, 'Unicorn'),
  ('pet_dragon', 140, 'Dragon'),
  ('pet_phoenix', 140, 'Phoenix'),
  ('pet_griffin', 140, 'Griffin cub'),
  ('pet_kitsune', 140, 'Nine-tailed fox'),
  ('pet_kraken', 140, 'Baby kraken'),
  ('pet_cloud_sprite', 140, 'Cloud sprite'),
  ('pet_moon_rabbit', 140, 'Moon rabbit'),
  ('plant_fern', 25, 'Fern'),
  ('plant_succulent', 25, 'Succulent'),
  ('plant_cactus', 25, 'Cactus'),
  ('plant_bonsai', 25, 'Bonsai'),
  ('plant_orchid', 25, 'Orchid'),
  ('plant_sunflower', 25, 'Sunflower'),
  ('plant_tulip', 25, 'Tulip'),
  ('plant_bamboo', 25, 'Bamboo'),
  ('plant_ivy', 25, 'Ivy'),
  ('plant_aloe', 25, 'Aloe vera'),
  ('plant_lavender', 25, 'Lavender'),
  ('plant_venus_flytrap', 25, 'Venus flytrap'),
  ('plant_money_tree', 25, 'Money tree'),
  ('plant_peace_lily', 25, 'Peace lily'),
  ('plant_moss_terrarium', 25, 'Moss terrarium');
